version: "3.9"

services:
  db:
    image: postgres:14.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    #restart: always
    build:
      context: .
    command: celery -A finance beat
    volumes:
      - .:/code
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
      - web

