# Generated by Django 3.2.13 on 2022-04-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__latest__')
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет')),
                ('prognosis', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Прогноз')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='account.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_code', models.IntegerField(db_index=True, unique=True, verbose_name='Цифр. код')),
                ('let_code', models.CharField(max_length=3, verbose_name='Букв. код')),
                ('units', models.IntegerField(verbose_name='Единиц')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['let_code'],
            },
        ),
        migrations.CreateModel(
            name='PayOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('isExpenditure', models.BooleanField(default=True, verbose_name='Тип')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='account.account', verbose_name='Аккаунт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='account.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['account', 'creation_date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='accounts', related_query_name='account', to='account.Currency'),
        ),
    ]
