# Generated by Django 3.2.13 on 2022-04-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='payout',
            name='description',
            field=models.CharField(default='Описание', max_length=30, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='payout',
            name='isFastRecord',
            field=models.BooleanField(default=False, verbose_name='Быстрая запись'),
        ),
        migrations.CreateModel(
            name='CategoryPrognosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Прогноз')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prognose',
                                                 to='account.category', verbose_name='Прогноз')),
            ],
        ),
    ]
