# Generated by Django 4.0.3 on 2022-03-30 23:18

from django.db import migrations
import requests
import xml.etree.ElementTree as ET


def fillUp(apps, schema_editor):
    # Типы - наш перечень, который будет вставлен в БД
    # Попросим Django вытащить модель - класс ClientTypes из аппликейшена user_profile
    Account = apps.get_model("account", "Account")
    CustomUser = apps.get_model("users", "CustomUser")
    Currency = apps.get_model("account", "Currency")
    Category = apps.get_model("account", "Category")

    doc = requests.get('http://www.cbr.ru/scripts/XML_daily.asp')
    doc.encoding = 'utf-8'
    doc = ET.fromstring(doc.content)
    for currency in doc:
        num_code = currency.find('NumCode').text
        let_code = currency.find('CharCode').text
        units = currency.find('Nominal').text
        name = currency.find('Name').text
        rate = currency.find('Value').text
        rate = rate.replace(',', '.')
        rate = float(rate)
        # print(numCode, let_code, units, name, rate)
        cur = Currency(num_code=num_code, let_code=let_code, units=units, name=name, rate=rate)
        cur.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.RunPython(fillUp),
    ]