# Generated by Django 4.0.3 on 2022-03-30 23:18

from django.db import migrations


def account(apps, schema_editor):
    # Типы - наш перечень, который будет вставлен в БД
    # Попросим Django вытащить модель - класс ClientTypes из аппликейшена user_profile
    Account = apps.get_model("account", "Account")
    CustomUser = apps.get_model("users", "CustomUser")
    # Currency = apps.get_model("account", "Currency")

    # Теперь в цикле создаём экземпляры класса с указанными параметрами и сохраняем их
    for t in range(100):
        ac = Account(user=CustomUser.objects.get(pk=t+1), total=t*100)
        ac.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(account),
    ]
