# Generated by Django 3.2.13 on 2022-05-15 12:34

from django.db import migrations

def fillUp(apps, schema_editor):
    # Типы - наш перечень, который будет вставлен в БД
    # Попросим Django вытащить модель - класс ClientTypes из аппликейшена user_profile
    Account = apps.get_model("account", "Account")
    CustomUser = apps.get_model("users", "CustomUser")
    Currency = apps.get_model("account", "Currency")
    Category = apps.get_model("account", "Category")
    PayOut = apps.get_model("account", "PayOut")
    CategoryPrognosis = apps.get_model("account", "CategoryPrognosis")
    for t in range(100):
        ac = Account(user=CustomUser.objects.get(pk=t+1), total=t*100)
        ac.save()
        ac.currencies.add(Currency.objects.get(let_code='USD'))
        ac.currencies.add(Currency.objects.get(let_code='EUR'))
        cat = Category(title='Еда', color='#ffffff', account=ac, prognosis=t * 100)
        cat.save()
        catPred = CategoryPrognosis(categoryId=cat, value=t * 100)
        catPred.save()
        cat = Category(title='Транспорт', color='#ffffff', account=ac, prognosis=t * 100)
        cat.save()
        catPred = CategoryPrognosis(categoryId=cat, value=t * 100)
        catPred.save()
        cat = Category(title='Кредит', color='#ffffff', account=ac, prognosis=t * 100)
        cat.save()
        catPred = CategoryPrognosis(categoryId=cat, value=t * 100)
        catPred.save()
        for r in range(100):
            payout = PayOut(account=ac, description="Пополнение", category=cat, value=r * 10,
                            isExpenditure=True, isFastRecord=False)
            payout.save()
            payout = PayOut(account=ac, description="Траты", category=cat, value=r * 5,
                            isExpenditure=False, isFastRecord=False)
            payout.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220428_1512'),
    ]

    operations = [
        migrations.RunPython(fillUp),
    ]
