# Generated by Django 3.2.13 on 2022-05-26 17:39
from datetime import datetime
import random

from django.db import migrations

def fillUp(apps, schema_editor):
    PayOut = apps.get_model("account", "PayOut")
    CategoryPrognosis = apps.get_model("account", "CategoryPrognosis")

    payouts = PayOut.objects.all()
    prognoses = CategoryPrognosis.objects.all()

    for prognosis in prognoses:
        prognosis.creation_date = datetime(year=2022, month=3, day=1)
        prognosis.save()

    for payout in payouts:
        day = random.randint(1, 30)
        month = random.randint(3, 5)
        date = datetime(year=2022, month=month, day=day)
        payout.creation_date = date
        payout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_payout_creation_date'),
    ]

    operations = [
        migrations.RunPython(fillUp),
    ]
