# Generated by Django 3.2.13 on 2022-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220526_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
