# Generated by Django 4.0.3 on 2022-03-30 23:18

from django.db import migrations

# Generated by Django 2.2.5 on 2019-12-28 10:07

# Добавляем models, чтобы Django могло создавать экземпляры нужных нам классов
from django.db import migrations, models


# Пишем функцию, которая будет вызываться при вызове этого файла миграции
# Название функции произвольное, должно принимать два параметра, как тут
def users(apps, schema_editor):
    # Типы - наш перечень, который будет вставлен в БД
    # Попросим Django вытащить модель - класс ClientTypes из аппликейшена user_profile
    CustomUser = apps.get_model("users", "CustomUser")

    # Теперь в цикле создаём экземпляры класса с указанными параметрами и сохраняем их
    for t in range(100):
        Cu = CustomUser(username='test_user' + str(t), email='test_user' + str(t) + '@test.com',
                        password='test_user' + str(t) + '@test.com')
        Cu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(users),
    ]
